---
kind: List
apiVersion: v1
id: cassandra-setup
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: cassandra
    labels:
      name: cassandra-svc
  spec:
    ports:
    - name: cql
      port: 9042
      targetPort: 9042
    selector:
      name: cassandra-pod
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      name: cassandra-rc
    name: cassandra-rc
  spec:
    replicas: 3
    selector:
      name: cassandra-pod
    template:
      metadata:
        name: cassandra-pod
        labels:
          name: cassandra-pod
      spec:
        containers:
        - name: cassandra
          image: quay.io/draft/k8s-cassandra:2.1.8_v1.2
          resources:
            requests:
              cpu: 4
              memory: 8Gi
          env:
          - name: MAX_HEAP_SIZE
            value: 1024M
          - name: HEAP_NEWSIZE
            value: 256M
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 9042
            name: cql
          - containerPort: 9160
            name: thrift
          volumeMounts:
          - name: data
            mountPath: /cassandra_data/data
          - name: commitlog
            mountPath: /cassandra_data/commitlog
          - name: savedcaches
            mountPath: /cassandra_data/saved_caches
          - name: log
            mountPath: /cassandra_data/log
        volumes:
        - name: data
          emptyDir: {}
        - name: commitlog
          emptyDir: {}
        - name: savedcaches
          emptyDir: {}
        - name: log
          emptyDir: {}

